# Generated by Django 3.1.7 on 2021-02-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('ho', 'home'), ('pe', 'personal'), ('wo', 'work')], default='ho', max_length=2),
        ),
        migrations.AddField(
            model_name='note',
            name='note_info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
