# Generated by Django 3.1.7 on 2021-02-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='completed',
            new_name='complete',
        ),
    ]
