# Generated by Django 3.1.7 on 2021-02-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20210223_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_info',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
